services:
  postgres:
    image: postgres:17-alpine
    container_name: exchange_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-exchange}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: exchange_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: exchange_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .:/app
    env_file:
      - .env  # Загружаем переменные из .env
    command: [ "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  bot:
    build: .
    container_name: exchange_bot
    environment:
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .:/app
    env_file:
      - .env  # Загружаем переменные из .env
    command: [ "python", "-m", "bot.main" ]

volumes:
  postgres_data:
  mongodb_data: